name: Setup SSH Config
description: Setup SSH config and key with painless
inputs:
  ssh_key_base64:
    description: "Base64 encoded SSH private key"
    required: true
  ssh_user:
    description: "SSH username"
    required: true
  ssh_host:
    description: "SSH host or IP"
    required: true
  ssh_port:
    description: "SSH port"
    required: false
    default: "22"
  ssh_identity_file_name:
    description: "File name for ssh_key"
    required: false
    default: "key.pem"
  ssh_alias:
    description: "Alias for ssh host"
    required: false
    default: "ssh-host"
runs:
  using: composite
  steps:
    - shell: "bash"
      run: |
       # make ssh dir
       mkdir -p "~/.ssh";

       # decode ssh key and change permission
       echo ${{ inputs.ssh_key_base64 }} | base64 -d > "~/.ssh/${{ inputs.ssh_identity_file_name }}";
       chmod 600 "~/.ssh/${{ inputs.ssh_identity_file_name }}";

       # setup ssh config
       echo <<EOF > "~/.ssh/config"
       Host ${{ inputs.ssh_alias }}
         HostName ${{ inputs.ssh_host }}
         Port ${{ inputs.ssh_port }}
         User ${{ inputs.ssh_user }}
         IdentityFile ~/.ssh/${{ inputs.ssh_identity_file_name }}
         StrictHostKeyChecking no
       EOF
     
